# Generated by Django 5.1.2 on 2024-12-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_datas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water_data',
            name='data_detection',
        ),
    ]
