# Generated by Django 5.1.2 on 2024-12-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_detections', '0001_initial'),
        ('water_datas', '0002_remove_water_data_data_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_data',
            name='data_detection',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_detections.data_detection'),
            preserve_default=False,
        ),
    ]
