# Generated by Django 5.1.2 on 2024-12-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_detections', '0001_initial'),
        ('water_datas', '0003_water_data_data_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_data',
            name='data_detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_detections.data_detection'),
        ),
    ]
