# Generated by Django 5.1.2 on 2024-12-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_types', '0003_alter_custom_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_type',
            name='name',
            field=models.CharField(choices=[('Soil', 'Soil'), ('Water', 'Water'), ('Air', 'Air')], max_length=55),
        ),
    ]
