# Generated by Django 5.1.2 on 2024-12-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_datas', '0002_initial'),
        ('custom_types', '0004_alter_custom_type_name'),
        ('soil_datas', '0001_initial'),
        ('water_datas', '0002_remove_water_data_data_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_type',
            name='user',
        ),
        migrations.AddField(
            model_name='custom_type',
            name='air',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='air_datas.air_data'),
        ),
        migrations.AddField(
            model_name='custom_type',
            name='soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soil_datas.soil_data'),
        ),
        migrations.AddField(
            model_name='custom_type',
            name='water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='water_datas.water_data'),
        ),
        migrations.AlterField(
            model_name='custom_type',
            name='name',
            field=models.CharField(choices=[('Water', 'Water'), ('Soil', 'Soil'), ('Air', 'Air')], max_length=55),
        ),
    ]
