# Generated by Django 5.1.2 on 2024-12-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_types', '0005_remove_custom_type_user_custom_type_air_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_type',
            name='air',
        ),
        migrations.RemoveField(
            model_name='custom_type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='custom_type',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='custom_type',
            name='water',
        ),
        migrations.AddField(
            model_name='custom_type',
            name='type',
            field=models.CharField(choices=[('1', 'Soil'), ('2', 'Water'), ('3', 'Air')], default='1', max_length=2),
        ),
    ]
