# Generated by Django 5.1.2 on 2024-12-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_types', '0006_remove_custom_type_air_remove_custom_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_type',
            name='type',
            field=models.CharField(choices=[('Water', 'Water'), ('Soil', 'Soil'), ('Air', 'Air')], default='Water', max_length=55),
        ),
    ]
