# Generated by Django 5.1.2 on 2024-12-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduinos', '0003_alter_arduino_description_alter_arduino_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduino',
            name='user',
        ),
    ]
