# Generated by Django 5.1.2 on 2024-12-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_region_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='user',
        ),
    ]
